    global:
      scrape_interval: 3s

    scrape_configs:
      - job_name: 'nginx-exporter'
        static_configs:
          - targets: ['nginx_exporter:9113']

      - job_name: 'train_model_api'
        metrics_path: /metrics
        static_configs:
          - targets: ['mlops-nginx-train-model-api:8000']
    