global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'train-api'
    static_configs:
      - targets: ['train-model-api:8000']

  - job_name: 'predict-api'
    static_configs:
      - targets: ['predict-api:8000']

  - job_name: 'mlflow'
    static_configs:
      - targets: ['mlflow:5000']

  - job_name: 'airflow'
    static_configs:
      - targets: ['airflow-webserver:8080']
    